site_name: Musicando
repo_url: https://github.com/TiagoTi/musicando
repo_name: musicando
edit_uri: tree/main/docs

theme:
  name: 'material'
  language: 'pt-BR'
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [musicando]