[tool.poetry]
name = "musicando"
version = "0.1.0"
description = ""
authors = ["tiago.cipriano <tiago.cipriano@luilzalabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
