name: Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v4
      - name: Outro
        run: echo $(ls)