name: Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v4
      - name: Baixa python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar Poetry
        run: pip install poetry
      - name: Instalar dependencias Poetry
        run: poetry install --without doc
      - name: Test
        run: poetry run task test
